name: product-quality

on:
  pull_request:

permissions:
  contents: read

jobs:
  audit-quality:
    uses: des1re10/Libraries/.github/workflows/product-quality.yml@test
    with:
      libraries_ref: test
    secrets:
      libraries_pat: ${{ secrets.LIBRARIES_PAT }}
